// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeoFindR.Infrastructure;

namespace NeoFindR.Migrations
{
    [DbContext(typeof(FindRContext))]
    [Migration("20191010153901_agents")]
    partial class agents
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NeoFindR.Domain.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ActiveStatus");

                    b.Property<Guid?>("CacheId");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateModified");

                    b.Property<int>("EntityStatus");

                    b.Property<DateTime>("LastCrashed");

                    b.Property<DateTime>("LastRebooted");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CacheId");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("NeoFindR.Domain.Cache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ActiveStatus");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateModified");

                    b.Property<int>("EntityStatus");

                    b.HasKey("Id");

                    b.ToTable("Cache");
                });

            modelBuilder.Entity("NeoFindR.Domain.Inhabitant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ActiveStatus");

                    b.Property<string>("CurrentThreatLevel");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateModified");

                    b.Property<int>("EntityStatus");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<DateTime>("LastSlept");

                    b.HasKey("Id");

                    b.ToTable("Inhabitants");
                });

            modelBuilder.Entity("NeoFindR.Domain.Agent", b =>
                {
                    b.HasOne("NeoFindR.Domain.Cache", "Cache")
                        .WithMany()
                        .HasForeignKey("CacheId");
                });
#pragma warning restore 612, 618
        }
    }
}
